### ISSUE TITLE
Missing dependencies 

### ISSUE THREAD

**Issue by cAstraea** [srijanreddy98/crowd-analyitcs#1]
Hello, 
Think it's missing some files ? Tried to run on my machine and getting Error: /usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'people_count/people_count.py': [Errno 2] No such file or directory

**Comment by srijanreddy98** [comment]
Hey @cAstraea . We are actually in the process of shifting it from tensorflow in python to tfjs as we want the analytics to happen in the client side. This is why we removed people count. I have re-uploaded it. You might hit through a lot of errors. This project requires python3. You can install all the python/conda dependencies from environment.yml file.
